version: "3.4"
services:
  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootUser
      MONGO_INITDB_ROOT_PASSWORD: passRootUser
      MONGO_INITDB_DATABASE: app
    volumes:
      # todo - "${PWD}/db/init.js:/docker-entrypoint-initdb.d/init.mongo.js:ro"
      - "mongo-data:/data/db"
    ports:
      - 27017:27017

  backend:
    container_name: backend
    hostname: backend
    image: zhenik/ocn-backend:1.0
    command: [
      "./application",
      "-Dquarkus.http.host=0.0.0.0",
      "-Dquarkus.mongodb.connection-string=mongodb://rootUser:passRootUser@mongo:27017",
      "-Dquarkus.mongodb.database=app",
      "-Dquarkus.http.cors=true",
      "-Dquarkus.http.cors.methods=GET,PUT,POST",
      "-Dquarkus.http.proxy-address-forwarding=true",
      "-Dquarkus.http.allow-forwarded=true",
      "-Dquarkus.http.cors.access-control-max-age=24H"
      #"-Dquarkus.http.cors.origins=http://localhost:3000,http://localhost,http://54.171.115.231:3000,http://54.171.115.231"
    ]
    ports:
      - 8080:8080
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.official
    image: zhenik/ocn-frontend:1.0
    volumes:
      - "./nginx.old.conf:/etc/nginx/nginx.conf"
    ports:
      - 3000:80

#  frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile.official2
#    image: zhenik/ocn-frontend:1.0
#    ports:
#      - 3000:8080

volumes:
  mongo-data:
    name: "mongo-data"
