version: "3.4"
services:
  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootUser
      MONGO_INITDB_ROOT_PASSWORD: passRootUser
      MONGO_INITDB_DATABASE: app
    volumes:
      # todo - "${PWD}/db/init.js:/docker-entrypoint-initdb.d/init.mongo.js:ro"
      - "mongo-data:/data/db"
    ports:
      - 27017:27017

  backend-ocn:
    container_name: backend
    hostname: backend
    image: zhenik/ocn-backend:1.01
    command: [
      "./application",
      "-Dquarkus.http.host=0.0.0.0",
      "-Dquarkus.http.root-path=/api/v1/",
      "-Dquarkus.mongodb.connection-string=mongodb://rootUser:passRootUser@mongo:27017",
      "-Dquarkus.mongodb.database=app",
      "-Dquarkus.http.cors=true",
      "-Dquarkus.http.cors.methods=GET,PUT,POST",
      "-Dquarkus.http.cors.access-control-max-age=24H",
      "-Dquarkus.http.cors.origins=http://localhost:3000,http://localhost:4000"
    ]
    ports:
      - 8888:8080
    depends_on:
      - mongo

  frontend-ocn-game-on:
    build:
      context: .
      dockerfile: Dockerfile.official
      target: prod-gamefied
    image: zhenik/ocn-frontend:1.22-on
    volumes:
      - "./default-with-auth.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - backend-ocn

  frontend-ocn-game-off:
    build:
      context: .
      dockerfile: Dockerfile.official
      target: prod-non-gamefied
    image: zhenik/ocn-frontend:1.22-off
    volumes:
      - "./default-with-auth.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 4001:3000
    depends_on:
      - mongo
      - backend-ocn

  auth-guard:
    container_name: auth-guard
    build:
      context: auth-guard
      dockerfile: Dockerfile
    image: zhenik/auth-guard:1.1
    volumes:
      - "./auth-guard/project-credentials.json:/usr/src/app/project-credentials.json"
#    ports:
#      - 8080:8080

volumes:
  mongo-data:
    name: "mongo-data"
