FROM node:13 as build-stage
WORKDIR /app
COPY package*.json ./
RUN yarn install
ENV VUE_APP_API_URL $VUE_APP_API_URL
COPY ./ .
RUN yarn run build

FROM nginx as production-stage
RUN apt-get update && apt-get install -y \
  curl
RUN mkdir /app
COPY --from=build-stage /app/dist /app
#COPY nginx.conf /etc/nginx/nginx.conf
