version: "3.4"
services:
  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootUser
      MONGO_INITDB_ROOT_PASSWORD: passRootUser
      MONGO_INITDB_DATABASE: app
    ports:
      - 27017:27017

  backend-ocn:
    container_name: backend-ocn
    hostname: backend
    image: zhenik/ocn-backend:1.0
    command: [
      "./application",
      "-Dquarkus.http.host=0.0.0.0",
      "-Dquarkus.mongodb.connection-string=mongodb://rootUser:passRootUser@mongo:27017",
      "-Dquarkus.mongodb.database=app",
      "-Dquarkus.http.cors=true",
      "-Dquarkus.http.cors.methods=GET,PUT,POST",
      "-Dquarkus.http.proxy-address-forwarding=true",
      "-Dquarkus.http.allow-forwarded=true",
      "-Dquarkus.http.cors.access-control-max-age=24H",
      "-Dquarkus.http.cors.origins=http://0.0.0.0:3000,http://localhost:3000"
#      "-Dquarkus.http.cors.origins=http://localhost:3000,http://localhost,http://54.171.115.231:3000,http://54.171.115.231"
    ]
    ports:
      - 8888:8080
    depends_on:
      - mongo

  frontend-ocn:
    container_name: frontend-ocn
    image: zhenik/ocn-frontend:1.0
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 3080:80
      - 3000:3000
      - 3001:3001 # crutch currently
